node {
	stage('Git checkout') {
	git branch: 'main' , url: 'https://github.com/JonasRF/projeto-dsdeliver.git'
            }

        stage('Printing Hello Word'){ 
        echo "Pipeline Usando Jenkinsfile"
            }

	stage('Printing Hello Word'){ 
                echo "Hello World!"
	}
     }
  
